export enum StatusCodeEnum {
  OK = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
}

export enum ErrorCodeEnum {
  BAD_REQUEST = 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND'
}
export enum CustomErrorCodeEnum {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  MISSING_TICKER_OR_NAME = 'MISSING_TICKER_OR_NAME',
  INSTRUMENT_NOT_FOUND = 'INSTRUMENT_NOT_FOUND',
  PRICE_REQUIRED_FOR_LIMIT_ORDER = 'PRICE_REQUIRED_FOR_LIMIT_ORDER'
}